name: Run shortbet
on:
  push:
  pull_request:
  schedule:
    - cron: "05 9 * * 1" # every monday at 9:05 am
  workflow_dispatch:
    inputs:
      full_run:
        description: "Whether to execute a full run of all tickers."
        required: True
        default: True
        type: boolean

jobs:
  scheduled:
    if: ${{  github.event_name == 'pull_request' || github.event_name == 'schedule' || github.ref == 'refs/heads/master'}}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install packages (not development)
        run: poetry install --no-dev

      - name: Run scheduled
        if: ${{ github.event_name == 'schedule'}}
        run: poetry run python main.py

      - name: Run manually
        if: ${{ github.event_name != 'schedule' && github.ref == 'refs/heads/master' }}
        run: poetry run python main.py

      - uses: lassebenni/publish-to-github-action@master
        if: ${{ github.event_name == 'schedule' || github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
